server:
  port: 8855
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./test  # Removed the semicolon
  jpa:
    hibernate:
      ddl-auto: update  # Use update in production
